language: python
matrix:
  include:
    - python: '3.8'
      env: TOXENV=flake8

    - python: '3.6'
      env: TOXENV=py36
    - python: '3.7'
      env: TOXENV=py37
    - python: '3.8'
      env: TOXENV=py38
    # Python 3.9 is not available in Travis yet.
    # - python: '3.9'
    #   env: TOXENV=py39
    - python: 'pypy3'
      env: TOXENV=pypy3
install:
  - pip install tox
script:
  - tox -v
